### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by davidbucsu** [Tronic/cmake-modules#6]
Hi!
This repo is super useful and I'd like to include `LibFindMacros.cmake` in my (commercial) project.
It's stated in the comment that it is public domain.
Would you mind adding a licence to the project here on GitHub so it's explicitly stated?
Thanks in advance!

**Comment by Tronic** [comment]
Added to README.

**Comment by davidbucsu** [comment]
Thank you very much @Tronic for doing it so fast!
However if I might ask (pretty please :slightly_smiling_face:) would you add the license like this?
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
It's very straightforward, only a few clicks.
You might want to select `The Unlicense` type which is about the most permissive [public-domain-equivalent](https://en.wikipedia.org/wiki/Public-domain-equivalent_license) license out there.
I would be super grateful :slightly_smiling_face: and thank you again!
![image](https://user-images.githubusercontent.com/62461203/197699486-fb7597fa-0ece-41d8-b7fa-89240f5c804b.png)

**Comment by Tronic** [comment]
As you probably are aware, Public Domain works can be used and modified without license or credit to anyone. As such, you can simply add LibFindMacros to your own project and claim it as your own work, put any license you want on it. Basically do anything you wish with it with no restriction.

As stated in the comment closing the PR, I don't want to clutter this project with license files where none are needed. A lot of wording where a lawyer would be needed to make sense if that actually is public domain or whether there are some subtle differences. Frankly, it is much better to simply keep it public domain, a millennia old concept that everyone easily understands.

If your legal department thinks that this is not good enough, e.g. in a jurisdiction where Public Domain is not recognized by law, you should tell them that they are idiots because no court would have any problem determining what Public Domain means. There is simply no precedent because no-one would question it in court.

I hope this helps, cheers! :)
